version: "3"

services:

  grobid:
    image: grobid/grobid:0.8.2-crf
    ports:
      - "8070:8070"

  grobid-analysis:
    build: .
    volumes:
      - .:/Analisis-over-articles-using-Grobid
    depends_on:
      - grobid